Allow access to exceptions that caused disconnections from the server
jstedfast/MailKit pull request #1342
Opened 2022-02-27 17:31 UTC by Mcphylus12

HI I work in a team that works with the library and its worked great so thanks. Recently we came across an issue that was difficult to diagnose and upon solving the problem by aggregating and analysing outputs of the protocol logger we realised we had been disconnected and the hook provided did not provide details on why we had been disconnected. (It was google bouncing as we didnt have a header filled out correctly). 

The proposed changes allows the OnDisconnected override and event to access the exception that caused a Disconnect in the event it happens. 

- I could not find the best place to put tests in for this case but would be happy to work on the PR given any suggestions .
- The current implementation is a breaking change but im happy to make changes if theres a preference to how this could be introduced in a non breaking manner.

2022-03-02 14:56 UTC, jstedfast commented
I'll try to look into this more closely soon. I've just been really busy lately.

2022-03-04 23:44 UTC, jstedfast requested changes

2022-03-04 23:44 UTC, jstedfast commented on MailKit/DisconnectedEventArgs.cs
>  		{
This breaks API. Would be better to add a new .ctor()

2022-03-04 23:44 UTC, jstedfast commented on MailKit/MailService.cs
>  	/// <summary>
Undo all of the above auto-sorting changes

2022-03-04 23:44 UTC, jstedfast commented on MailKit/MailService.cs
>  		}
This breaks API again :(

Not sure what a good way to get around this would be...

2022-03-04 23:44 UTC, jstedfast commented on MailKit/Net/Smtp/SmtpClient.cs
>  			}
Should this really be the SmtpCommandException? Or should it really be the generic Exception that was caught here?

Semantically, if the `Exception` property on DisconnectedEventArgs is to adhere to the documented expectation, then this should be the Exception raised by the `RSET` command, no?

I sort of understand why you carried it over from the DATA/BDAT command, but I think that could be confusing?

Or is this where you are getting the exception in your use-case?

2022-03-04 23:46 UTC, jstedfast commented on MailKit/DisconnectedEventArgs.cs
>  		{
Something like this:

```diff
@@ -53,6 +55,23 @@ namespace MailKit
                        IsRequested = requested;
                }

+               /// <summary>
+               /// Initializes a new instance of the <see cref="T:MailKit.DisconnectedEventArgs"/> class.
+               /// </summary>
+               /// <remarks>
+               /// Initializes a new instance of the <see cref="T:MailKit.DisconnectedEventArgs"/> class.
+               /// </remarks>
+               /// <param name="host">The name of the host that the client was connected to.</param>
+               /// <param name="port">The port that the client was connected to.</param>
+               /// <param name="options">The SSL/TLS options that were used by the client.</param>
+               /// <param name="requested">If <c>true</c>, the <see cref="IMailService"/> was disconnected via the
+               /// <see cref="IMailService.Disconnect(bool, System.Threading.CancellationToken)"/> method.</param>
+               /// <param name="exception">The exception that caused the client to disconnect.</param>
+               public DisconnectedEventArgs (string host, int port, SecureSocketOptions options, bool requested, Exception exception) : this (host, port, options, requested)
+               {
+                       Exception = exception;
+               }
+
                /// <summary>
                /// Get whether or not the service was explicitly asked to disconnect.
                /// </summary>
@@ -66,5 +85,16 @@ namespace MailKit
```

2022-03-04 23:47 UTC, jstedfast commented
I can probably massage this up with my suggested changes (in fact, already have them massaged locally).

What I don't really know yet is how to get around breaking API in MailService or what the right behavior is for the RSET thing.

2022-03-05 01:42 UTC, jstedfast commented
Getting IMAP and POP3 to set the Exception property doesn't seem to be quite as trivial as SMTP.

2022-03-11 11:59 UTC, Mcphylus12 commented on MailKit/Net/Smtp/SmtpClient.cs
>  			}
it was just about getting access to the exception that causes the initial problem. my understanding is the exception caught here would not necessarily contain the information that triggered the reset but instead contain information on why the reset failed

2022-03-11 12:07 UTC, Mcphylus12 commented
Sorry for the delay my ability to look continue with this is a bit sporadic. if you have a version of this youd prefer i had not particular attachment to how i did it.

regarding the teh exceptions using inner exceptions would seems like the straight forward solution. if rset throws an exception we can pass the data exception through to it as the inner. then nothing is lost.

On the breaking api changes i could only suggest having another set of overloads for all the ondisconnect work or exposing this in a new OnReset hook.

and regarding IMAP and POP3 my knowledge is too shallow in these areas i only work with the library in the context of the SMTP. is it possible to have this isolated to SMTP or would a solution need to cover all bases

2022-03-12 20:57 UTC, Mcphylus12 commented
> I looked into doing this for IMAP and POP3 but it was awkward and non-trivial.
> 
> Here's what I'm thinking...
> 
> Maybe `MailService` could get a `protected virtual void OnDisconnected (DisconnectedEventArgs args)` method that the old method could call once instantiating the `DisconnectedEventArgs`.
> 
> Then I'm thinking that there would be an `SmtpDisconnectedEventArgs` that adds the `Exception` property.
> 
> **Edit:**
> 
> Crap. That breaks API if someone is already subclassing SmtpClient and overrides the current OnDisconnected() method.
> 
> Question: If you wrap your `Send()` (or `SendAsync()` call in try/catch, you _should_ already get access to this exception because it would get thrown.
> 
> Isn't that good enough? I mean, I understand that it's not as convenient in your situation where you are likely handling this in the event handler, but you also only really needed this for debugging purposes, right?

We managed to get a situation where the disconection seemed to be happening due to a proactive  message from the server and the stack trace dumped in the OnDisconnect Hook did not originate in our system (ie we would throw inside our onDisconnect hook and it would just vanish). 

Ill close this and attempt to put together a test app that reproduced the exact scenario where this was occurring as typing it out and looking at the code it doesnt seem possible.

2022-03-12 20:57 UTC, closed without merging